baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Veelim Blog'
theme = 'paper'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
   tag = "tags"
   category = "categories"